steps:
  - name: gcr.io/cloud-builders/gsutil
    args: [cp, gs://$PROJECT_ID-misc/prod.secret.exs, ./config/prod.secret.exs]
  - name: gcr.io/cloud-builders/docker
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker build -q -t gcr.io/$PROJECT_ID/wiki-backend .
        container_id=$$(docker create gcr.io/$PROJECT_ID/wiki-backend)
        docker cp ${container_id}:/app/start_release /releases/start_release
  - name: gcr.io/cloud-builders/gsutil
    args: [cp, /releases/start_release, gs://$PROJECT_ID-releases/release]
  - name: gcr.io/cloud-builders/gcloud
    args: [
        beta,
        compute,
        instance-groups,
        managed,
        rolling-action,
        restart,
        wiki-group,
        --min-ready,
        3m,
        --max-unavailable,
        1
        --zone=us-central1-f,
      ]
options:
  volumes:
    - name: "releases"
      path: "/releases"
