steps:
  - name: gcr.io/cloud-builders/gsutil
    args: [cp, gs://$PROJECT_ID-misc/prod.env, /releases/prod.env]
  - name: gcr.io/cloud-builders/docker
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker build --env-file /releases/prod.env -t gcr.io/$PROJECT_ID/wiki-backend .
        container_id=$$(docker create gcr.io/$PROJECT_ID/wiki-backend)
        docker cp ${container_id}:/app/start_release /releases/start_release
  - name: gcr.io/cloud-builders/gsutil
    args: [cp, /releases/start_release, gs://$PROJECT_ID-releases/release]
  - name: gcr.io/cloud-builders/gcloud
    args:
      [
        compute,
        instance-groups,
        managed,
        rolling-action,
        restart,
        wiki-group,
        --region=us-central1-f,
      ]
options:
  volumes:
    - name: "releases"
      path: "/releases"
